// \--- Part Two ---
// ----------
//
// With your analysis of the manifold complete, you begin fixing the teleporter. However, as you open the side of the teleporter to replace the broken manifold, you are surprised to discover that it isn't a classical tachyon manifold - it's a *quantum tachyon manifold*.
//
// With a quantum tachyon manifold, only a *single tachyon particle* is sent through the manifold. A tachyon particle takes *both* the left and right path of each splitter encountered.
//
// Since this is impossible, the manual recommends the many-worlds interpretation of quantum tachyon splitting: each time a particle reaches a splitter, it's actually *time itself* which splits. In one timeline, the particle went left, and in the other timeline, the particle went right.
//
// To fix the manifold, what you really need to know is the *number of timelines* active after a single particle completes all of its possible journeys through the manifold.
//
// In the above example, there are many timelines. For instance, there's the timeline where the particle always went left:
//
// ```
// .......S.......
// .......|.......
// ......|^.......
// ......|........
// .....|^.^......
// .....|.........
// ....|^.^.^.....
// ....|..........
// ...|^.^...^....
// ...|...........
// ..|^.^...^.^...
// ..|............
// .|^...^.....^..
// .|.............
// |^.^.^.^.^...^.
// |..............
//
// ```
//
// Or, there's the timeline where the particle alternated going left and right at each splitter:
//
// ```
// .......S.......
// .......|.......
// ......|^.......
// ......|........
// ......^|^......
// .......|.......
// .....^|^.^.....
// ......|........
// ....^.^|..^....
// .......|.......
// ...^.^.|.^.^...
// .......|.......
// ..^...^|....^..
// .......|.......
// .^.^.^|^.^...^.
// ......|........
//
// ```
//
// Or, there's the timeline where the particle ends up at the same point as the alternating timeline, but takes a totally different path to get there:
//
// ```
// .......S.......
// .......|.......
// ......|^.......
// ......|........
// .....|^.^......
// .....|.........
// ....|^.^.^.....
// ....|..........
// ....^|^...^....
// .....|.........
// ...^.^|..^.^...
// ......|........
// ..^..|^.....^..
// .....|.........
// .^.^.^|^.^...^.
// ......|........
//
// ```
//
// In this example, in total, the particle ends up on *`40`* different timelines.
//
// Apply the many-worlds interpretation of quantum tachyon splitting to your manifold diagram. *In total, how many different timelines would a single tachyon particle end up on?*

use std::collections::{HashMap, HashSet};

fn solution(input: &str) -> usize {
    let mut lines_iter = input.lines();

    let first_line = lines_iter.next().unwrap();
    let manifold_idx = first_line.find('S').unwrap();

    let mut beam_idxs = HashMap::from([(manifold_idx, 1)]);

    for line in lines_iter {
        let mut stopped_beam_idxs = HashSet::new();
        let mut new_beam_idxs = HashMap::new();

        for (beam_idx, beam_timeline_count) in &beam_idxs {
            let c = line.chars().nth(*beam_idx).unwrap();
            match c {
                '.' => { /* continue movement */ }
                '^' => {
                    stopped_beam_idxs.insert(*beam_idx);
                    new_beam_idxs
                        .entry(*beam_idx - 1)
                        .and_modify(|timeline_count| *timeline_count += beam_timeline_count)
                        .or_insert(*beam_timeline_count);
                    new_beam_idxs
                        .entry(*beam_idx + 1)
                        .and_modify(|timeline_count| *timeline_count += beam_timeline_count)
                        .or_insert(*beam_timeline_count);
                }
                _ => unreachable!(),
            }
        }

        for idx in stopped_beam_idxs {
            beam_idxs.remove(&idx);
        }
        for (idx, beam_timeline_count) in new_beam_idxs {
            beam_idxs
                .entry(idx)
                .and_modify(|timeline_count| *timeline_count += beam_timeline_count)
                .or_insert(beam_timeline_count);
        }
    }

    beam_idxs.values().sum()
}

#[test]
fn test_example() {
    let input = indoc::indoc!(
        r#"
        .......S.......
        ...............
        .......^.......
        ...............
        ......^.^......
        ...............
        .....^.^.^.....
        ...............
        ....^.^...^....
        ...............
        ...^.^...^.^...
        ...............
        ..^...^.....^..
        ...............
        .^.^.^.^.^...^.
        ...............
        "#
    );

    assert_eq!(40, solution(input));
}

#[test]
fn test_input() {
    let input = std::fs::read_to_string("input.txt").unwrap();

    assert_eq!(1537373473727, solution(&input));
}
